# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-25 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_schedule', '0002_slot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionrole',
            name='submitted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
