# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-20 07:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0002_speaker_twitter_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='annotation',
            field=models.TextField(blank=True, verbose_name='Annotation'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='invite_email',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='Invite_email'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='invite_token',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Invite token'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
