# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-10 16:46
from __future__ import unicode_literals

from django.db import migrations


def move_speakers_to_subclass(apps, schema_editor):
    ''' Replaces all of the concrete 'Speaker' objects with 'DefaultSpeaker'
    objects. '''

    SpeakerBase = apps.get_model('symposion_speakers', 'SpeakerBase')
    DefaultSpeaker = apps.get_model('symposion_speakers', 'DefaultSpeaker')

    for speaker in SpeakerBase.objects.all():
        ds = DefaultSpeaker(_twitter_username=speaker.twitter_username)
        ds.speakerbase_ptr = speaker
        ds.save()

class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0003_auto_20170810_1644'),
    ]

    operations = [
        migrations.RunPython(move_speakers_to_subclass),
    ]
