# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-10 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0005_auto_20170810_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultspeaker',
            name='id',
        ),
        migrations.AlterField(
            model_name='defaultspeaker',
            name='speakerbase_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='symposion_speakers.SpeakerBase'),
        ),
    ]
