# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-10 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0006_auto_20170810_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultspeaker',
            old_name='_twitter_username',
            new_name='twitter_username',
        ),
        migrations.RemoveField(
            model_name='speakerbase',
            name='twitter_username',
        ),
    ]
