# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-25 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Commented at'),
        ),
        migrations.AlterField(
            model_name='latestvote',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Submitted at'),
        ),
        migrations.AlterField(
            model_name='proposalmessage',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Submitted at'),
        ),
        migrations.AlterField(
            model_name='resultnotification',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='review',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Submitted at'),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Assigned at'),
        ),
    ]
