# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-10 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposalresult',
            old_name='minus_one',
            new_name='strong_reject',
        ),
        migrations.RenameField(
            model_name='proposalresult',
            old_name='minus_zero',
            new_name='weak_reject',
        ),
        migrations.RenameField(
            model_name='proposalresult',
            old_name='plus_one',
            new_name='strong_accept',
        ),
        migrations.RenameField(
            model_name='proposalresult',
            old_name='plus_zero',
            new_name='weak_accept',
        ),
        migrations.AddField(
            model_name='proposalresult',
            name='abstain',
            field=models.PositiveIntegerField(default=0, verbose_name='Abstain'),
        ),
        migrations.AlterField(
            model_name='latestvote',
            name='vote',
            field=models.CharField(choices=[('+2', '++ \u2014 Good proposal and I will argue for it to be accepted.'), ('+1', '+ \u2014 OK proposal, but I will not argue for it to be accepted.'), ('-1', '\u2212 \u2014 Weak proposal, but I will not argue strongly against acceptance.'), ('-2', '\u2212- \u2014 Serious issues and I will argue to reject this proposal.'), ('0', 'Abstain - I do not want to review this proposal and I do not want to see it again.')], max_length=2, verbose_name='Vote'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='vote',
            field=models.CharField(blank=True, choices=[('+2', '++ \u2014 Good proposal and I will argue for it to be accepted.'), ('+1', '+ \u2014 OK proposal, but I will not argue for it to be accepted.'), ('-1', '\u2212 \u2014 Weak proposal, but I will not argue strongly against acceptance.'), ('-2', '\u2212- \u2014 Serious issues and I will argue to reject this proposal.'), ('0', 'Abstain - I do not want to review this proposal and I do not want to see it again.')], max_length=2, verbose_name='Vote'),
        ),
    ]
