# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-10 22:00
from __future__ import unicode_literals

from django.db import migrations

VOTES = {
    "+1" : "++",
    "+0" : "+",
    "-0" : "-",
    "-1" : "--",
    "0" : "0",
}


def convert_votes(apps, schema_editor):
    LatestVote = apps.get_model('symposion_reviews', 'LatestVote')
    Review = apps.get_model('symposion_reviews', 'Review')
    for vote in LatestVote.objects.all():
        vote.vote = VOTES[vote.vote]
        vote.save()
    for review in Review.objects.all():
        review.vote = VOTES[review.vote]
        review.save()


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_reviews', '0002_auto_20170810_2141'),
    ]

    operations = [
        migrations.RunPython(convert_votes),
    ]
