# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-10 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_reviews', '0003_auto_20170810_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestvote',
            name='vote',
            field=models.CharField(choices=[('++', '++ : Good proposal and I will argue for it to be accepted.'), ('+', '+ : OK proposal, but I will not argue for it to be accepted.'), ('-', '\u2212 : Weak proposal, but I will not argue strongly against acceptance.'), ('--', '\u2212- : Serious issues and I will argue to reject this proposal.'), ('0', 'Abstain : I do not want to review this proposal and I do not want to see it again.')], max_length=2, verbose_name='Vote'),
        ),
        migrations.AlterField(
            model_name='proposalresult',
            name='strong_accept',
            field=models.PositiveIntegerField(default=0, verbose_name='Strong accept'),
        ),
        migrations.AlterField(
            model_name='proposalresult',
            name='strong_reject',
            field=models.PositiveIntegerField(default=0, verbose_name='Strong reject'),
        ),
        migrations.AlterField(
            model_name='proposalresult',
            name='weak_accept',
            field=models.PositiveIntegerField(default=0, verbose_name='Weak accept'),
        ),
        migrations.AlterField(
            model_name='proposalresult',
            name='weak_reject',
            field=models.PositiveIntegerField(default=0, verbose_name='Weak reject'),
        ),
        migrations.AlterField(
            model_name='review',
            name='vote',
            field=models.CharField(blank=True, choices=[('++', '++ : Good proposal and I will argue for it to be accepted.'), ('+', '+ : OK proposal, but I will not argue for it to be accepted.'), ('-', '\u2212 : Weak proposal, but I will not argue strongly against acceptance.'), ('--', '\u2212- : Serious issues and I will argue to reject this proposal.'), ('0', 'Abstain : I do not want to review this proposal and I do not want to see it again.')], max_length=2, verbose_name='Vote'),
        ),
    ]
