# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-08-11 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalsection',
            name='anonymous',
            field=models.BooleanField(default=False, help_text='If this option is switched on, reviewers will not be able to see the names of the proposers or coproposers of any proposal in this section.', verbose_name='Anonymous review'),
        ),
    ]
